### ISSUE TITLE
Connection test fails if no data is present in the database being tested.

### ISSUE THREAD

**Issue by RickyGrassmuck** [jenkinsci/influxdb-query-plugin#18]
Seems to be the same issue as #17, if you setup your configuration to point to a brand new database without anything in it, the connection test will fail with a null pointer exception due to not having any results.
```
Client error : Database Error
java.lang.NullPointerException
        at org.joeo.plugins.influxquery.DescriptorImpl.doTestConnection(DescriptorImpl.java:134)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
```
From https://github.com/jenkinsci/influxdb-query-plugin/blob/master/src/main/java/org/joeo/plugins/influxquery/DescriptorImpl.java#L128
```
128         InfluxDB influxDBClient = null;
129         try {
130             influxDBClient = InfluxDBUtils.getConnection(influxURL, influxDB, influxUser, influxPWD);
131             Query query = new Query("show measurements", influxDB);
132             LOGGER.info("Testing query from Jenkins Plugin with url:{}, db:{}", influxURL, influxDB);
133             QueryResult result = influxDBClient.query(query);
134             int numMeasurements = result.getResults().get(0).getSeries().get(0).getValues().size();
135             LOGGER.info("Connection Successful. Found {} measurements", numMeasurements);
136             return FormValidation.ok("Connection Successful.  Found " + numMeasurements + " Measurements");
137
138         } catch (Exception e) {
139             LOGGER.error("Error testing connection with url({}), influxDB({}), influxUser({}), got error : {}", influxURL, influxDB,influxUser,
140                     e.getMessage(), e);
141             if (e.getMessage() != null) {
142                 return FormValidation.error(e, "Client error : " + e.getMessage());
143             }
144             return FormValidation.error(e, "Client error : Database Error");
```

You addressed this same behavior in the main logic but since the connection test (really it's a query test more then a connection test) implements it's own logic it still suffers from the behavior.

**Comment by JoeOffenberg** [comment]
Thanks.  Ill take a look.
